name: mary
favicon: null
layout_spectrum: 0.24659
typography_spectrum: 0.8384307343512774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.625
  lightness: 0.0927686661016196
  saturation: 0.662383277900517
  rhythmicContrast: 0.36312990239821374
purpose: []
